name: Build and Release Extension Charts

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release tag'

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-charts:
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@release-2.9
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: gh-pages
      tagged_release: ${{ github.event.inputs.release }}